service: capacitor-stripe-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  environment:
    TZ: Asia/Tokyo
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
